### PR TITLE
Scaventum/update version requirement

### PR DESCRIPTION
**Pull request by scaventum**
Hello, just want to propose this new requirements for laravel 6.

* update version requirement

### CODE REVIEW

**Comment by bestmomo** [comment]
Hello !

Thanks for your PR but there is an issue, this command is from an additional package and I can't get it easily. I use **Artisan::all()** to access all commands and I only get core ones.

When checking on last Laravel 6 I have another strange issue with **route:list** command that don't show the list.

Also there are many new commands to add for Laravel 6 so I must better check the update.

**Comment by scaventum** [comment]
> When checking on last Laravel 6 I have another strange issue with route:list command that don't show the list.

This one does not happen to me, i'm using 6.11 though.

`php artisan` only shows , but it still shows the commands by vendor packages i installed. Where did you get the new commands documentation?

**Comment by bestmomo** [comment]
For the new commands nice artisan gets automaticaly all stuff

**Comment by pjhartin** [comment]
I also noticed that Artisan::call based commands seem to miss routes declared by service providers. To replicate, simply install laravel telescope or laravel nova and run any Artisan::call('migrate') command. You will notice that the command does not pick up on all commands, only core.

**Comment by pjhartin** [comment]
Ignore my previous comment, it seems v6.15 has caused issues with `Artisan::call` which has broken functionality for this package - https://github.com/laravel/framework/issues/31485

**Pull request closed without merging**
