### PR TITLE
Don't count() undefined .

### PR DESCRIPTION
**Pull request by davvblack**

### CODE REVIEW

**Comment by davvblack** [comment]
This fixes an issue where, with notices on, the template throws an error exception when there are no $errors.

**Comment by bestmomo** [comment]
Hi, I cant get this issue, could you tell me with which command ?

**Comment by davvblack** [comment]
It happens for me, php 7.1.7, laravel 5.3, therefore nice-artisan 0.5.

https://gist.github.com/davvblack/c4cb978a78af2362995324cf082f8091
screen shot 2017-09-13 at 5 55 41 pm

**Comment by bestmomo** [comment]
I cant update V0.5 because it's now on V1 but I never got this issue on Laravel 5.3

**Comment by davvblack** [comment]
I can reproduce this error in version 1.0 as well.  I can fix it in my app by setting error_reporting(0); in Illuminate\Support\ServiceProvider\AppServiceProvider::boot(), but fixing the notice seems more correct to me.  Do you see any drawback of this patch?

**Comment by bestmomo** [comment]
No drawback, merged.

**Pull request merged**
