### PR TITLE
Allow Laravel 8

### PR DESCRIPTION
**Pull request by jgrunder**
Let me know if something is missing

### CODE REVIEW

**Comment by bestmomo** [comment]
Hello,

Thank you for your PR but miss these commands : 

- 'make:cast',
- 'queue:batches-table',
- 'queue:retry-batch',

Greetings

**Comment by jgrunder** [comment]
I wasn't sure as these commands are not in the Laravel 8 Upgrade guide :)

**Comment by bestmomo** [comment]
There are always commands added that do not appear in the upgrade guide ;)

**Comment by jgrunder** [comment]
Good to know, I'll check all missing commands for the next update :) Thank you!

**Pull request merged**
